import type { Product } from "./types";

export const bases: Product[] = [
  {
    id: "base-1",
    slug: "base-noir-classic",
    category: "base",
    name: "Основа Noir Classic",
    price: 6500,
    description:
      "Классическая чёрная основа из плотной экокожи. Универсальная форма «полумесяц», магнитная застёжка.",
    image: "/img/base-1.svg",
    color: "Чёрный",
    material: "Экокожа",
    inStock: true,
    tags: ["база", "ежедневная"],
  },
  {
    id: "base-2",
    slug: "base-graphite-moon",
    category: "base",
    name: "Основа Graphite Moon",
    price: 6900,
    description: "Графитовая основа округлой формы. Хорошо держит форму, без подкладки.",
    image: "/img/base-2.svg",
    color: "Графит",
    material: "Экокожа",
    inStock: true,
    tags: ["база"],
  },
  {
    id: "base-3",
    slug: "base-shadow-crescent",
    category: "base",
    name: "Основа Shadow Crescent",
    price: 7200,
    description: "Структурный полумесяц с прострочкой по краю. Чёрная замша.",
    image: "/img/base-3.svg",
    color: "Чёрный",
    material: "Замша",
    inStock: true,
    tags: ["база", "вечер"],
  },
  {
    id: "base-4",
    slug: "base-bone-white",
    category: "base",
    name: "Основа Bone White",
    price: 6800,
    description: "Светлая основа цвета слоновой кости. Подходит к ярким и тёмным мешкам.",
    image: "/img/base-4.svg",
    color: "Молочный",
    material: "Экокожа",
    inStock: true,
    tags: ["база", "светлая"],
  },
  {
    id: "base-5",
    slug: "base-iron-rose",
    category: "base",
    name: "Основа Iron Rose",
    price: 7400,
    description: "Тёмно-розовая основа с матовой фактурой. Лёгкая и прочная.",
    image: "/img/base-5.svg",
    color: "Розовый",
    material: "Экокожа",
    inStock: true,
    tags: ["база", "акцент"],
  },
  {
    id: "base-6",
    slug: "base-blood-velvet",
    category: "base",
    name: "Основа Blood Velvet",
    price: 7900,
    description: "Глубокий бордовый бархат. Готическая основа для вечерних сборок.",
    image: "/img/base-6.svg",
    color: "Бордовый",
    material: "Бархат",
    inStock: true,
    tags: ["база", "вечер"],
  },
  {
    id: "base-7",
    slug: "base-night-pebble",
    category: "base",
    name: "Основа Night Pebble",
    price: 6600,
    description: "Маленькая мини-основа. Поместится телефон и карты.",
    image: "/img/base-7.svg",
    color: "Чёрный",
    material: "Экокожа",
    inStock: true,
    tags: ["база", "мини"],
  },
  {
    id: "base-8",
    slug: "base-silver-fog",
    category: "base",
    name: "Основа Silver Fog",
    price: 7100,
    description: "Серая основа с лёгким металлическим напылением.",
    image: "/img/base-8.svg",
    color: "Серый",
    material: "Экокожа",
    inStock: false,
    tags: ["база"],
  },
  {
    id: "base-9",
    slug: "base-charcoal-square",
    category: "base",
    name: "Основа Charcoal Square",
    price: 7300,
    description: "Квадратная основа с резкой геометрией. Угольный цвет.",
    image: "/img/base-9.svg",
    color: "Чёрный",
    material: "Экокожа",
    inStock: true,
    tags: ["база", "форма"],
  },
  {
    id: "base-10",
    slug: "base-mystic-oval",
    category: "base",
    name: "Основа Mystic Oval",
    price: 7600,
    description: "Овальная основа из плотной матовой кожи с прострочкой звёзд.",
    image: "/img/base-10.svg",
    color: "Чёрный",
    material: "Кожа",
    inStock: true,
    tags: ["база", "акцент"],
  },
];

export const bags: Product[] = [
  {
    id: "bag-1",
    slug: "bag-mustard-pouch",
    category: "bag",
    name: "Мешок Mustard Pouch",
    price: 3200,
    description: "Горчичный мешок-кисет на затяжке. Лёгкая ткань, мягкая форма.",
    image: "/img/bag-1.svg",
    color: "Горчичный",
    material: "Текстиль",
    inStock: true,
    tags: ["мешок", "яркий"],
  },
  {
    id: "bag-2",
    slug: "bag-blood-red",
    category: "bag",
    name: "Мешок Blood Red",
    price: 3400,
    description: "Алый мешок из плотного хлопка. Контрастный акцент.",
    image: "/img/bag-2.svg",
    color: "Красный",
    material: "Хлопок",
    inStock: true,
    tags: ["мешок", "акцент"],
  },
  {
    id: "bag-3",
    slug: "bag-noir-classic",
    category: "bag",
    name: "Мешок Noir Classic",
    price: 3100,
    description: "Базовый чёрный мешок. Подходит к любой основе.",
    image: "/img/bag-3.svg",
    color: "Чёрный",
    material: "Текстиль",
    inStock: true,
    tags: ["мешок", "база"],
  },
  {
    id: "bag-4",
    slug: "bag-bone-cream",
    category: "bag",
    name: "Мешок Bone Cream",
    price: 3300,
    description: "Мягкий молочный мешок с фактурой льна.",
    image: "/img/bag-4.svg",
    color: "Молочный",
    material: "Лён",
    inStock: true,
    tags: ["мешок", "светлый"],
  },
  {
    id: "bag-5",
    slug: "bag-rose-thorn",
    category: "bag",
    name: "Мешок Rose Thorn",
    price: 3500,
    description: "Розовый мешок с вышитыми шипами. Fairy goth настроение.",
    image: "/img/bag-5.svg",
    color: "Розовый",
    material: "Текстиль",
    inStock: true,
    tags: ["мешок", "акцент"],
  },
  {
    id: "bag-6",
    slug: "bag-witch-violet",
    category: "bag",
    name: "Мешок Witch Violet",
    price: 3600,
    description: "Тёмно-фиолетовый бархатный мешок. Густой цвет.",
    image: "/img/bag-6.svg",
    color: "Фиолетовый",
    material: "Бархат",
    inStock: true,
    tags: ["мешок", "вечер"],
  },
  {
    id: "bag-7",
    slug: "bag-emerald-spell",
    category: "bag",
    name: "Мешок Emerald Spell",
    price: 3700,
    description: "Изумрудный мешок-кисет. Хорошо смотрится с чёрной основой.",
    image: "/img/bag-7.svg",
    color: "Зелёный",
    material: "Текстиль",
    inStock: true,
    tags: ["мешок", "яркий"],
  },
  {
    id: "bag-8",
    slug: "bag-silver-mesh",
    category: "bag",
    name: "Мешок Silver Mesh",
    price: 4100,
    description: "Сетчатый серебристый мешок с подкладкой. Эффект сцены.",
    image: "/img/bag-8.svg",
    color: "Серебро",
    material: "Сетка",
    inStock: false,
    tags: ["мешок", "вечер"],
  },
  {
    id: "bag-9",
    slug: "bag-shadow-grey",
    category: "bag",
    name: "Мешок Shadow Grey",
    price: 3000,
    description: "Серый базовый мешок. Сдержанный универсал.",
    image: "/img/bag-9.svg",
    color: "Серый",
    material: "Текстиль",
    inStock: true,
    tags: ["мешок", "база"],
  },
  {
    id: "bag-10",
    slug: "bag-flame-orange",
    category: "bag",
    name: "Мешок Flame Orange",
    price: 3400,
    description: "Огненный оранжевый мешок. Яркий акцент для тёмной основы.",
    image: "/img/bag-10.svg",
    color: "Оранжевый",
    material: "Текстиль",
    inStock: true,
    tags: ["мешок", "акцент"],
  },
];

export const straps: Product[] = [
  {
    id: "strap-1",
    slug: "strap-silver-chain",
    category: "strap",
    name: "Ремень Silver Chain",
    price: 2400,
    description: "Серебристая цепь среднего звена. Длина 120 см.",
    image: "/img/strap-1.svg",
    color: "Серебро",
    material: "Металл",
    inStock: true,
    tags: ["ремень", "цепь"],
  },
  {
    id: "strap-2",
    slug: "strap-pearl-line",
    category: "strap",
    name: "Ремень Pearl Line",
    price: 2900,
    description: "Жемчужный ремень. Подходит к светлым и тёмным основам.",
    image: "/img/strap-2.svg",
    color: "Жемчуг",
    material: "Жемчуг",
    inStock: true,
    tags: ["ремень", "акцент"],
  },
  {
    id: "strap-3",
    slug: "strap-leather-black",
    category: "strap",
    name: "Ремень Leather Black",
    price: 2200,
    description: "Чёрный кожаный ремень с регулируемой длиной.",
    image: "/img/strap-3.svg",
    color: "Чёрный",
    material: "Кожа",
    inStock: true,
    tags: ["ремень", "база"],
  },
  {
    id: "strap-4",
    slug: "strap-spiked-collar",
    category: "strap",
    name: "Ремень Spiked Collar",
    price: 3100,
    description: "Кожаный ремень с шипами. Панк-настроение.",
    image: "/img/strap-4.svg",
    color: "Чёрный",
    material: "Кожа",
    inStock: true,
    tags: ["ремень", "панк"],
  },
  {
    id: "strap-5",
    slug: "strap-rose-ribbon",
    category: "strap",
    name: "Ремень Rose Ribbon",
    price: 1900,
    description: "Розовая шёлковая лента. Завязывается узлом.",
    image: "/img/strap-5.svg",
    color: "Розовый",
    material: "Шёлк",
    inStock: true,
    tags: ["ремень", "акцент"],
  },
  {
    id: "strap-6",
    slug: "strap-iron-chain",
    category: "strap",
    name: "Ремень Iron Chain",
    price: 2600,
    description: "Тёмная гремучая цепь крупного звена.",
    image: "/img/strap-6.svg",
    color: "Графит",
    material: "Металл",
    inStock: true,
    tags: ["ремень", "цепь"],
  },
  {
    id: "strap-7",
    slug: "strap-velvet-band",
    category: "strap",
    name: "Ремень Velvet Band",
    price: 2300,
    description: "Бархатный ремень глубокого винного цвета.",
    image: "/img/strap-7.svg",
    color: "Бордовый",
    material: "Бархат",
    inStock: true,
    tags: ["ремень", "вечер"],
  },
  {
    id: "strap-8",
    slug: "strap-charm-chain",
    category: "strap",
    name: "Ремень Charm Chain",
    price: 3400,
    description: "Цепь с подвесками-звёздами. Декоративный ремень.",
    image: "/img/strap-8.svg",
    color: "Серебро",
    material: "Металл",
    inStock: false,
    tags: ["ремень", "декор"],
  },
  {
    id: "strap-9",
    slug: "strap-paracord",
    category: "strap",
    name: "Ремень Paracord",
    price: 1800,
    description: "Плетёный паракорд. Лёгкий и прочный.",
    image: "/img/strap-9.svg",
    color: "Чёрный",
    material: "Паракорд",
    inStock: true,
    tags: ["ремень", "база"],
  },
  {
    id: "strap-10",
    slug: "strap-mesh-net",
    category: "strap",
    name: "Ремень Mesh Net",
    price: 2100,
    description: "Эластичная сетка-плетёнка. Подходит для лёгких сборок.",
    image: "/img/strap-10.svg",
    color: "Чёрный",
    material: "Сетка",
    inStock: true,
    tags: ["ремень", "акцент"],
  },
];

export const decors: Product[] = [
  {
    id: "decor-1",
    slug: "decor-cat-charm",
    category: "decor",
    name: "Брелок Cat Charm",
    price: 1200,
    description: "Подвеска-кот в шипастом ошейнике. Маскот бренда.",
    image: "/img/decor-1.svg",
    color: "Белый",
    material: "Полимер",
    inStock: true,
    tags: ["декор", "маскот"],
  },
  {
    id: "decor-2",
    slug: "decor-pink-star",
    category: "decor",
    name: "Звезда Pink Star",
    price: 600,
    description: "Розовая звезда-патч на металлическом крепеже.",
    image: "/img/decor-2.svg",
    color: "Розовый",
    material: "Металл",
    inStock: true,
    tags: ["декор", "звезда"],
  },
  {
    id: "decor-3",
    slug: "decor-flame-patch",
    category: "decor",
    name: "Патч Flame",
    price: 700,
    description: "Фиолетовое пламя. Готический акцент.",
    image: "/img/decor-3.svg",
    color: "Фиолетовый",
    material: "Текстиль",
    inStock: true,
    tags: ["декор", "пламя"],
  },
  {
    id: "decor-4",
    slug: "decor-silver-cross",
    category: "decor",
    name: "Подвеска Silver Cross",
    price: 900,
    description: "Серебристый крест-подвеска. Звенит при ходьбе.",
    image: "/img/decor-4.svg",
    color: "Серебро",
    material: "Металл",
    inStock: true,
    tags: ["декор", "готика"],
  },
  {
    id: "decor-5",
    slug: "decor-bow-noir",
    category: "decor",
    name: "Бант Noir",
    price: 500,
    description: "Чёрный бархатный бант. Классика fairy goth.",
    image: "/img/decor-5.svg",
    color: "Чёрный",
    material: "Бархат",
    inStock: true,
    tags: ["декор", "бант"],
  },
  {
    id: "decor-6",
    slug: "decor-pearl-keyring",
    category: "decor",
    name: "Брелок Pearl",
    price: 800,
    description: "Жемчужный брелок-цепочка. Лёгкий акцент.",
    image: "/img/decor-6.svg",
    color: "Жемчуг",
    material: "Жемчуг",
    inStock: true,
    tags: ["декор", "жемчуг"],
  },
  {
    id: "decor-7",
    slug: "decor-spike-set",
    category: "decor",
    name: "Шипы Spike Set",
    price: 650,
    description: "Набор металлических шипов на клёпках. 6 штук.",
    image: "/img/decor-7.svg",
    color: "Серебро",
    material: "Металл",
    inStock: true,
    tags: ["декор", "панк"],
  },
  {
    id: "decor-8",
    slug: "decor-rose-pin",
    category: "decor",
    name: "Брошь Rose Pin",
    price: 750,
    description: "Розовая брошь-роза с шипами. Hand-made фишка.",
    image: "/img/decor-8.svg",
    color: "Розовый",
    material: "Полимер",
    inStock: true,
    tags: ["декор", "акцент"],
  },
  {
    id: "decor-9",
    slug: "decor-skull-charm",
    category: "decor",
    name: "Брелок Skull",
    price: 1000,
    description: "Серебряный череп на короткой цепочке.",
    image: "/img/decor-9.svg",
    color: "Серебро",
    material: "Металл",
    inStock: false,
    tags: ["декор", "готика"],
  },
  {
    id: "decor-10",
    slug: "decor-mini-stars",
    category: "decor",
    name: "Мини-звёзды",
    price: 450,
    description: "Россыпь мини-звёзд для самостоятельного крепления.",
    image: "/img/decor-10.svg",
    color: "Серебро",
    material: "Металл",
    inStock: true,
    tags: ["декор", "россыпь"],
  },
];

export const sets: Product[] = [
  {
    id: "set-1",
    slug: "set-classic-noir",
    category: "set",
    name: "Сборка Classic Noir",
    price: 12800,
    description: "Чёрная основа, чёрный мешок, кожаный ремень. Универсальный комплект.",
    image: "/img/set-1.svg",
    color: "Чёрный",
    material: "Микс",
    inStock: true,
    tags: ["сборка", "база"],
    setItems: {
      baseId: "base-1",
      bagId: "bag-3",
      strapId: "strap-3",
      decorIds: ["decor-5"],
    },
  },
  {
    id: "set-2",
    slug: "set-pink-witch",
    category: "set",
    name: "Сборка Pink Witch",
    price: 14200,
    description: "Розовая основа, мешок Rose Thorn, цепь и звезда.",
    image: "/img/set-2.svg",
    color: "Розовый",
    material: "Микс",
    inStock: true,
    tags: ["сборка", "акцент"],
    setItems: {
      baseId: "base-5",
      bagId: "bag-5",
      strapId: "strap-1",
      decorIds: ["decor-2", "decor-8"],
    },
  },
  {
    id: "set-3",
    slug: "set-blood-velvet",
    category: "set",
    name: "Сборка Blood Velvet",
    price: 15400,
    description: "Бордовая бархатная основа и фиолетовый мешок. Тёмная история.",
    image: "/img/set-3.svg",
    color: "Бордовый",
    material: "Микс",
    inStock: true,
    tags: ["сборка", "вечер"],
    setItems: {
      baseId: "base-6",
      bagId: "bag-6",
      strapId: "strap-7",
      decorIds: ["decor-3"],
    },
  },
  {
    id: "set-4",
    slug: "set-mustard-pop",
    category: "set",
    name: "Сборка Mustard Pop",
    price: 12400,
    description: "Графитовая основа и горчичный мешок. Контраст и характер.",
    image: "/img/set-4.svg",
    color: "Горчичный",
    material: "Микс",
    inStock: true,
    tags: ["сборка", "акцент"],
    setItems: {
      baseId: "base-2",
      bagId: "bag-1",
      strapId: "strap-9",
      decorIds: ["decor-1"],
    },
  },
  {
    id: "set-5",
    slug: "set-bone-light",
    category: "set",
    name: "Сборка Bone Light",
    price: 13100,
    description: "Светлая основа, льняной мешок и жемчужный ремень.",
    image: "/img/set-5.svg",
    color: "Молочный",
    material: "Микс",
    inStock: true,
    tags: ["сборка", "лето"],
    setItems: {
      baseId: "base-4",
      bagId: "bag-4",
      strapId: "strap-2",
      decorIds: ["decor-6"],
    },
  },
  {
    id: "set-6",
    slug: "set-iron-punk",
    category: "set",
    name: "Сборка Iron Punk",
    price: 15600,
    description: "Чёрная основа, шипастый ремень и набор шипов. Панк-настроение.",
    image: "/img/set-6.svg",
    color: "Чёрный",
    material: "Микс",
    inStock: true,
    tags: ["сборка", "панк"],
    setItems: {
      baseId: "base-3",
      bagId: "bag-3",
      strapId: "strap-4",
      decorIds: ["decor-7", "decor-4"],
    },
  },
  {
    id: "set-7",
    slug: "set-emerald-spell",
    category: "set",
    name: "Сборка Emerald Spell",
    price: 13800,
    description: "Тёмная основа, изумрудный мешок и серебряная цепь.",
    image: "/img/set-7.svg",
    color: "Зелёный",
    material: "Микс",
    inStock: true,
    tags: ["сборка", "вечер"],
    setItems: {
      baseId: "base-1",
      bagId: "bag-7",
      strapId: "strap-1",
      decorIds: ["decor-10"],
    },
  },
  {
    id: "set-8",
    slug: "set-flame-charm",
    category: "set",
    name: "Сборка Flame Charm",
    price: 13400,
    description: "Графитовая основа и огненный мешок с пламенным патчем.",
    image: "/img/set-8.svg",
    color: "Оранжевый",
    material: "Микс",
    inStock: true,
    tags: ["сборка", "акцент"],
    setItems: {
      baseId: "base-9",
      bagId: "bag-10",
      strapId: "strap-9",
      decorIds: ["decor-3"],
    },
  },
  {
    id: "set-9",
    slug: "set-mystic-stars",
    category: "set",
    name: "Сборка Mystic Stars",
    price: 14900,
    description: "Овальная основа, чёрный мешок и серебристая цепь с россыпью звёзд.",
    image: "/img/set-9.svg",
    color: "Чёрный",
    material: "Микс",
    inStock: true,
    tags: ["сборка", "звёзды"],
    setItems: {
      baseId: "base-10",
      bagId: "bag-3",
      strapId: "strap-1",
      decorIds: ["decor-10", "decor-2"],
    },
  },
  {
    id: "set-10",
    slug: "set-night-pebble-mini",
    category: "set",
    name: "Сборка Night Pebble Mini",
    price: 11500,
    description: "Мини-основа, чёрный мешок и паракорд. Лёгкий городской комплект.",
    image: "/img/set-10.svg",
    color: "Чёрный",
    material: "Микс",
    inStock: true,
    tags: ["сборка", "мини"],
    setItems: {
      baseId: "base-7",
      bagId: "bag-3",
      strapId: "strap-9",
      decorIds: ["decor-1"],
    },
  },
];

export const allProducts: Product[] = [
  ...bases,
  ...bags,
  ...straps,
  ...decors,
  ...sets,
];

export function getProductBySlug(slug: string): Product | undefined {
  return allProducts.find((p) => p.slug === slug);
}

export function getProductById(id: string): Product | undefined {
  return allProducts.find((p) => p.id === id);
}

export function getProductsByCategory(category: Product["category"]): Product[] {
  return allProducts.filter((p) => p.category === category);
}

export function isCompatible(
  product: Product,
  selectedBaseId: string | null,
): boolean {
  if (!selectedBaseId) return true;
  if (!product.compatibleWith || product.compatibleWith.length === 0)
    return true;
  return product.compatibleWith.includes(selectedBaseId);
}
